name: Erlang rebar CI

on:
  push:
    branches:
    - 1.2.x
  pull_request:
    branches:
    - 1.2.x

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: ["24.0", "23.3", "22.3", "21.3", "20.3", "19.3"]
    container:
      image: erlang:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make V=1 all
